name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ docker-sync ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
  DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
  
jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install manifest-tool
      run: |
        wget https://github.com/estesp/manifest-tool/releases/download/v2.2.1/binaries-manifest-tool-2.2.1.tar.gz
        tar -zxvf binaries-manifest-tool-2.2.1.tar.gz
        chmod +x manifest-tool-linux-amd64
        sudo mv manifest-tool-linux-amd64 /usr/local/bin/manifest-tool		
        
    - name: Install crane
      run: |
        curl -LO https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz
        tar -zxvf go-containerregistry_Linux_x86_64.tar.gz
        sudo mv crane /usr/local/bin/
        chmod a+x /usr/local/bin/crane
        crane version
        
    - name: Sync images using Skopeo (Python Fast Sync)
      run: python3 .github/scripts/sync.py
